on:
  workflow_dispatch:
  push:
    branches:
      - main
name:  Deploy website on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Use Node 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Build Project
        run: |
          npm install
          npm run build --prod     

      - name: FTP Deploy
        uses: sebastianpopp/ftp-action@v2.0.0
        with:
          host:  veroenterprises.com
          user: expressui.ftp
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: "./dist/ExpressUI/browser"
          
    
 
